from typing import Any, List, Optional, Tuple, Union
import numpy as np

def canny(image: np.ndarray, sigma: float = 1.0, low_threshold: Optional[float] = None, high_threshold: Optional[float] = None) -> np.ndarray: ...
def graycomatrix(image: np.ndarray, distances: List[int], angles: List[float], levels: int = 256, symmetric: bool = False, normed: bool = False) -> np.ndarray: ...
def graycoprops(P: np.ndarray, prop: str) -> np.ndarray: ... 